name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    env:
      - project: Mflex.InSiteXMLClient/Mflex.InSiteXMLClient.csproj
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.*

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack ${{env.project}} --output nuget-packages --configuration Release

      - name: Publish
        run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{secrets.NUGET_AUTH_TOKEN}} --source https://api.nuget.org/v3/index.json
